#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""make-manifest.py — content integrity manifest for this catalog.

Why this exists
---------------
A citation needs to identify *what exactly* was cited. A tag name is a pointer that
can be moved; a commit hash is exact but unreadable and host-specific. A content
manifest is the readable middle ground: every file's SHA-256, plus one digest over
the whole set, so a reader can re-derive the same value from a checkout.

What it is NOT
--------------
It is not a defence against a determined forger — a manifest that ships next to the
content it describes can always be regenerated by whoever changed the content. It is
a **detection** device for accidental drift (a truncated download, a partial
checkout, an unnoticed edit) and a **citation anchor** (the digest names a set of
bytes, so two people can confirm they hold the same bytes).

The one rule that matters
-------------------------
`--verify` must be able to fail. A verifier that cannot fail is the exact subject of
this catalog. It is exercised by a negative control in CI: one byte is flipped on a
copy, and the verification is required to report a mismatch.

Usage
-----
    python tools/make-manifest.py                 # write INTEGRITY.md + manifest.sha256
    python tools/make-manifest.py --check         # recompute and compare (exit 1 on drift)
    python tools/make-manifest.py --print-digest  # print only the set digest
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PY_FLOOR = (3, 9)

# Files that are outputs of this tool, and therefore cannot describe themselves.
SELF_OUTPUTS = {"INTEGRITY.md", "manifest.sha256"}

# Directories that are not content.
EXCLUDE_DIRS = {".git", "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache"}

# Set digest domain separation: makes it obvious which scheme produced a digest, so a
# future format change cannot be mistaken for content drift.
DOMAIN = b"silent-failure-catalog/manifest/v1\n"


def iter_files(root: Path, skipped: list):
    """Yield (path, relpath) for every content file, in a stable order.

    `skipped` is passed in rather than returned: this is a generator, so a value
    accumulated inside it would be re-emitted with every item and reported more than
    once. Exclusions are collected by the caller and reported, never dropped silently.
    """
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if any(part in EXCLUDE_DIRS for part in rel.parts):
            skipped.append((str(rel), "excluded directory"))
            continue
        if rel.as_posix() in SELF_OUTPUTS:
            skipped.append((str(rel), "tool output (cannot self-describe)"))
            continue
        yield p, rel


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def collect(root: Path):
    entries = []
    skipped = []
    for p, rel in iter_files(root, skipped):
        entries.append((rel.as_posix(), sha256_file(p)))
    entries.sort(key=lambda kv: kv[0])
    return entries, skipped


def set_digest(entries) -> str:
    h = hashlib.sha256()
    h.update(DOMAIN)
    for path, file_digest in entries:
        h.update(path.encode("utf-8"))
        h.update(b"\0")
        h.update(file_digest.encode("ascii"))
        h.update(b"\n")
    return h.hexdigest()


def fmt_size(n: int) -> str:
    return "%.1f KiB" % (n / 1024.0) if n >= 1024 else "%d B" % n


def hand_written_tail(path: Path) -> list:
    """The lines of INTEGRITY.md that this tool does not own.

    The generator owns the file up to and including the per-file digest table.
    Everything after it was written by a person — the archival note that carries
    the canonical citation is exactly that kind of content. Overwriting it would
    silently delete a citation anchor every time somebody regenerated the
    manifest: the tool would keep its hashes correct and quietly break the thing
    the manifest exists to support.

    The tail is only recognised when it is separated from the table by a blank
    line, so a stray trailing newline is not mistaken for a section.
    """
    if not path.is_file():
        return []
    lines = path.read_text(encoding="utf-8").splitlines()
    last_row = -1
    for i, line in enumerate(lines):
        if line.startswith("| `"):
            last_row = i
    if last_row < 0 or last_row + 1 >= len(lines) or lines[last_row + 1].strip():
        return []
    return lines[last_row + 1:]


def write_outputs(root: Path, entries, skipped) -> str:
    digest = set_digest(entries)
    total_bytes = sum((root / p).stat().st_size for p, _ in entries)

    manifest = "".join("%s  %s\n" % (d, p) for p, d in entries)
    (root / "manifest.sha256").write_text(manifest, encoding="utf-8", newline="\n")

    lines = []
    lines.append("# Integrity manifest")
    lines.append("")
    lines.append("Generated by `tools/make-manifest.py`. **Do not edit by hand.**")
    lines.append("")
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append("| **Set digest (SHA-256)** | `%s` |" % digest)
    lines.append("| **Files covered** | %d |" % len(entries))
    lines.append("| **Total size** | %s |" % fmt_size(total_bytes))
    lines.append("| **Scheme** | `silent-failure-catalog/manifest/v1` |")
    lines.append("")
    lines.append("The set digest is `SHA-256` over the domain-separation string, then one")
    lines.append("`<path>\\0<sha256>\\n` record per file, in ascending path order. Recompute it from")
    lines.append("any checkout with `python tools/make-manifest.py --check`.")
    lines.append("")
    lines.append("## What this proves, and what it does not")
    lines.append("")
    lines.append("**Proves:** the bytes you hold match the bytes recorded here. It detects a")
    lines.append("truncated download, a partial checkout, or an edit that was not regenerated into")
    lines.append("this file.")
    lines.append("")
    lines.append("**Does not prove:** authorship, or that the content was ever correct. A manifest")
    lines.append("ships beside the content it describes, so anyone who changes the content can")
    lines.append("regenerate it. It anchors a *citation*; it does not attest *authorship*.")
    lines.append("")
    lines.append("## Files not covered")
    lines.append("")
    lines.append("`INTEGRITY.md` and `manifest.sha256` cannot describe themselves — a file whose hash")
    lines.append("appears inside itself is unsatisfiable. They are excluded, and that exclusion is")
    lines.append("listed here rather than left implicit.")
    lines.append("")
    lines.append("Directories excluded as non-content: %s." % ", ".join("`%s`" % d for d in sorted(EXCLUDE_DIRS)))
    lines.append("")
    lines.append("## Per-file digests")
    lines.append("")
    lines.append("| SHA-256 | Path |")
    lines.append("|---|---|")
    # NOTE: the loop variable is `file_digest`, not `digest`. Using `digest` here would
    # shadow the set digest computed above and make this function *return the hash of
    # the last file in the list* while still writing the correct value into
    # INTEGRITY.md. The printed number and the written number would then disagree —
    # a report that does not match the artifact it reports on. Found by this tool's own
    # verifier refusing to agree with its own generator.
    for path, file_digest in entries:
        lines.append("| `%s` | `%s` |" % (file_digest, path))
    lines.append("")

    integrity = root / "INTEGRITY.md"
    tail = hand_written_tail(integrity)
    content = "\n".join(lines)
    if tail:
        content = content.rstrip("\n") + "\n\n" + "\n".join(tail).rstrip("\n") + "\n"
    integrity.write_text(content, encoding="utf-8", newline="\n")
    if tail:
        print("note: preserved %d line(s) of hand-written content in "
              "INTEGRITY.md (after the digest table) that the generator does "
              "not own" % len(tail))

    if skipped:
        # Reported, not silent: an exclusion the reader cannot see is an exclusion that
        # will eventually hide something that mattered.
        print("note: %d path(s) excluded (reported, not silent):" % len(skipped))
        for rel, why in skipped:
            print("   %s  ← %s" % (rel, why))
    return digest


def verify(root: Path) -> int:
    mf = root / "manifest.sha256"
    if not mf.is_file():
        print("FAIL: manifest.sha256 is missing — run make-manifest.py to generate it")
        return 1

    recorded = {}
    for lineno, line in enumerate(mf.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        parts = line.split("  ", 1)
        if len(parts) != 2:
            print("FAIL: manifest.sha256 line %d is malformed: %r" % (lineno, line))
            return 1
        recorded[parts[1]] = parts[0]

    entries, _ = collect(root)
    current = {p: d for p, d in entries}

    missing = sorted(set(recorded) - set(current))
    added = sorted(set(current) - set(recorded))
    changed = sorted(p for p in set(current) & set(recorded) if current[p] != recorded[p])

    if missing or added or changed:
        print("FAIL: manifest does not match the working tree")
        for p in changed:
            print("   modified: %s" % p)
        for p in added:
            print("   not in manifest: %s" % p)
        for p in missing:
            print("   in manifest but absent: %s" % p)
        print("   (%d modified, %d added, %d absent)" % (len(changed), len(added), len(missing)))
        print("   If the change is intended, regenerate with tools/make-manifest.py.")
        return 1

    digest = set_digest(entries)
    # Cross-check the digest against INTEGRITY.md as well, so the two files cannot drift
    # apart while both looking internally fine.
    integ = root / "INTEGRITY.md"
    if not integ.is_file():
        print("FAIL: INTEGRITY.md is missing")
        return 1
    if digest not in integ.read_text(encoding="utf-8"):
        print("FAIL: INTEGRITY.md does not record the current set digest %s" % digest)
        print("      manifest.sha256 matches, but the human-readable file is stale.")
        return 1

    print("OK: %d file(s) verified, set digest %s" % (len(entries), digest))
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Content integrity manifest for this catalog.")
    ap.add_argument("--root", default=str(ROOT), help="repository root (default: repo root)")
    ap.add_argument("--check", action="store_true",
                    help="recompute and compare against manifest.sha256 / INTEGRITY.md; "
                         "exit 1 on any drift")
    ap.add_argument("--print-digest", action="store_true", help="print only the set digest")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve()

    if args.print_digest:
        entries, _ = collect(root)
        print(set_digest(entries))
        return 0

    if args.check:
        return verify(root)

    entries, skipped = collect(root)
    digest = write_outputs(root, entries, skipped)
    print("wrote INTEGRITY.md + manifest.sha256")
    print("%d file(s), set digest %s" % (len(entries), digest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
